# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web" 
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/infra" 
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/studio" 
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "dev"
