import { RiClipboardLine as VolunteerApplicationIcon } from 'react-icons/ri'

const STATUS_OPTIONS = [
  {title: 'Submitted', value: 'submitted'},
  {title: 'Assigned', value: 'assigned'},
  {title: 'Denied', value: 'denied'},
  {title: 'Withdrawn', value: 'withdrawn'},
  {title: 'Expired', value: 'expired'}
]

export default {
  name: 'volunteerApplication',
  type: 'document',
  title: 'Volunteer Application',
  icon: VolunteerApplicationIcon,
  liveEdit: true,
  fields: [
    {
      name: 'applicationId',
      type: 'string',
      title: 'Application ID',
      description: 'Unique identifier for the application. Intended to be generated by backend workflow logic.'
    },
    {
      name: 'position',
      type: 'reference',
      title: 'Volunteer position',
      to: [{type: 'volunteerRole'}],
      validation: Rule => Rule.required().error('Select the volunteer position for this application.')
    },
    {
      name: 'applicantName',
      type: 'string',
      title: 'Applicant name',
      validation: Rule => Rule.required().error('Applicant name is required.')
    },
    {
      name: 'applicantEmail',
      type: 'string',
      title: 'Applicant email',
      validation: Rule =>
        Rule.required()
          .email()
          .error('A valid applicant email is required.')
    },
    {
      name: 'applicantPhone',
      type: 'string',
      title: 'Applicant phone'
    },
    {
      name: 'hasPerformedRoleBefore',
      type: 'boolean',
      title: 'Has performed role before'
    },
    {
      name: 'referral',
      type: 'string',
      title: 'Referral'
    },
    {
      name: 'notes',
      type: 'text',
      title: 'Notes',
      rows: 4
    },
    {
      name: 'status',
      type: 'string',
      title: 'Status',
      initialValue: 'submitted',
      options: {
        list: STATUS_OPTIONS,
        layout: 'radio'
      },
      validation: Rule => Rule.required().error('Set an application status.')
    },
    {
      name: 'isActive',
      type: 'boolean',
      title: 'Active application',
      initialValue: true,
      description: 'Set false when this application should be archived or inactive in operational queues.',
      validation: Rule =>
        Rule.required().custom(value =>
          value === true || value === false ? true : 'Set active to true or false.'
        )
    },
    {
      name: 'submittedAt',
      type: 'datetime',
      title: 'Submitted at',
      initialValue: () => new Date().toISOString(),
      validation: Rule => Rule.required().error('Submitted timestamp is required.')
    },
    {
      name: 'assignedAt',
      type: 'datetime',
      title: 'Assigned at',
      hidden: ({document}) => document?.status !== 'assigned'
    },
    {
      name: 'deniedAt',
      type: 'datetime',
      title: 'Denied at',
      hidden: ({document}) => document?.status !== 'denied'
    },
    {
      name: 'rejectedReasonPublic',
      type: 'text',
      title: 'Rejected reason (public)',
      description: 'Shown to the applicant when their application is rejected.',
      rows: 3,
      hidden: ({document}) => document?.status !== 'denied'
    },
    {
      name: 'rejectedReasonInternal',
      type: 'text',
      title: 'Rejected reason (internal)',
      description: 'Internal-only staff context for this rejection.',
      rows: 3,
      hidden: ({document}) => document?.status !== 'denied'
    },
    {
      name: 'withdrawnAt',
      type: 'datetime',
      title: 'Withdrawn at',
      hidden: ({document}) => document?.status !== 'withdrawn'
    },
    {
      name: 'expiredAt',
      type: 'datetime',
      title: 'Expired at',
      hidden: ({document}) => document?.status !== 'expired'
    },
    {
      name: 'lastActionAt',
      type: 'datetime',
      title: 'Last action at'
    },
    {
      name: 'lastActionBy',
      type: 'string',
      title: 'Last action by'
    },
    {
      name: 'adminNote',
      type: 'text',
      title: 'Admin note',
      rows: 3
    }
  ],
  preview: {
    select: {
      title: 'applicantName',
      email: 'applicantEmail',
      status: 'status',
      position: 'position.role.name',
      submittedAt: 'submittedAt'
    },
    prepare({title, email, status, position, submittedAt}) {
      const subtitleParts = [
        position || 'No position',
        status ? status.charAt(0).toUpperCase() + status.slice(1) : 'Submitted',
        submittedAt ? new Date(submittedAt).toLocaleString() : null,
        email || null
      ].filter(Boolean)

      return {
        title: title || 'Unnamed applicant',
        subtitle: subtitleParts.join(' | ')
      }
    }
  }
}
