export const volunteerNavBadgeStyle = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  minWidth: "34px",
  height: "16px",
  px: "0.35rem",
  borderRadius: "999px",
  fontSize: "10px",
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  color: "#1f7a3f",
  fontWeight: "heading",
  lineHeight: 1,
  backgroundColor: "#e8f7ec",
  border: "1px solid",
  borderColor: "rgba(31,122,63,0.35)",
  boxShadow: "none",
  pointerEvents: "none",
  zIndex: 2,
  WebkitTextStroke: 0,
  textShadow: "none",
};
